name: Original-Model

device: 'cuda:0'
data:
  dataset: METR-LA
  batch-size: 64

train:
  epochs: 50

optimizer:
  name: RMSprop
  Adam:
    lr: 0.01
    weight_decay: 0.0002
  RMSprop:
    lr: 0.01
    weight_decay: .001

loss:
  name: MaskedMSELoss

model:
  name: DCRNN
  STGCN:
    n_history: 12
    k_hop: 3
    n_node: 207
    t_cnv_krnl_sz: 3
    dims: [[1, 32, 64], [64, 32, 128]]
    dropout: 0.3
  DCRNN:
    n_hist: 12
    n_pred: 12
    hidden_size: 64
    num_nodes: 207
    k_hop: 3
    n_rnn_layers: 2
    input_dim: 2
    output_dim: 1
    cl_decay_steps: 3000
  DCRNN2:
    batch_size: 64
    enc_input_dim: 1
    dec_input_dim: 1
    max_diffusion_step: 2
    num_nodes: 207
    num_rnn_layers: 2
    rnn_units: 64
    seq_len: 12
    output_dim: 1

scheduler:
  name: MultiStepLR
  ReduceLROnPlateau:
    factor: 0.1
    patience: 0
    threshold: 0.005
    min_lr: 0.00001
  StepLR:
    step_size: 10
    gamma: 0.1
  MultiStepLR:
    milestones: [20, 30, 40, 50]
    gamma: 0.1