name: DCRNNMODEL

device: 'cuda:0'
data:
  dataset: METR-LA
  batch-size: 64

train:
  epochs: 100
  max_grad_norm: 5

optimizer:
  name: Adam
  Adam:
    lr: 0.001
    weight_decay: 0
    eps: 0.001
    amsgrad: true
  RMSprop:
    lr: 0.01
    weight_decay: 0.001

loss:
  name: MaskedMAELoss

model:
  name: DCRNNMODEL
  DCRNNMODEL:
    cl_decay_steps: 2000
    batch_size: 64
    enc_input_dim: 2
    dec_input_dim: 1
    max_diffusion_step: 2
    num_nodes: 207
    num_rnn_layers: 2
    rnn_units: 64
    seq_len: 12
    output_dim: 1

scheduler:
  name: MultiStepLR
  ReduceLROnPlateau:
    factor: 0.1
    patience: 0
    threshold: 0.001
    min_lr: 0.000001
  StepLR:
    step_size: 10
    gamma: 0.1
  MultiStepLR:
    milestones: [20, 30, 40, 50]
    gamma: 0.1