name: DCRNN

device: 'cuda:2'
data:
  dataset: METR-LA
  batch-size: 64

train:
  epochs: 100
  max_grad_norm: 5

optimizer:
  name: Adam
  Adam:
    lr: 0.0001
    weight_decay: 0.001
    eps: 0.001
    amsgrad: true
  RMSprop:
    lr: 0.01
    weight_decay: 0.001

loss:
  name: MaskedMAELoss

model:
  name: DCRNN
  DCRNN:
    n_pred: 12
    hidden_size: 64
    num_nodes: 207
    n_supports: 1
    k_hop: 2
    n_rnn_layers: 2
    input_dim: 2
    output_dim: 1
    cl_decay_steps: 1000

scheduler:
  name: ReduceLROnPlateau
  ReduceLROnPlateau:
    factor: 0.2
    patience: 5
    threshold: 0.001
    min_lr: 0.000001
  StepLR:
    step_size: 10
    gamma: 0.1
  MultiStepLR:
    milestones: [1, 5, 10, 15, 20]
    gamma: 0.1