name: DCRNN

data:
  dataset: METR-LA
  batch-size: 64

train:
  device: 'cuda:2'
  epochs: 100
  max_grad_norm: 5

optimizer:
  name: RMSprop
  Adam:
    lr: 0.001
    weight_decay: 0.0002
  RMSprop:
    lr: 0.01
    weight_decay: 0.001

loss:
  name: MaskedMSELoss

model:
  name: DCRNN
  DCRNN:
    n_hist: 12
    n_pred: 12
    hidden_size: 64
    num_nodes: 207
    n_supports: 2
    k_hop: 2
    n_rnn_layers: 3
    input_dim: 2
    output_dim: 1
    cl_decay_steps: 3000

scheduler:
  name: ReduceLROnPlateau
  ReduceLROnPlateau:
    factor: 0.1
    patience: 0
    threshold: 0.001
    min_lr: 0.00000001
  StepLR:
    step_size: 10
    gamma: 0.1
  MultiStepLR:
    milestones: [1, 5, 10, 15, 20]
    gamma: 0.1