name: Ours-LSTM

device: 2
data:
  dataset: METR-LA
  batch-size: 64
  input_dim: 2
  output_dim: 1

train:
  epochs: 100
  max_grad_norm: 5
  early_stop_steps: 10

optimizer:
  name: Adam
  Adam:
    lr: 0.001
    weight_decay: 0.001
  RMSprop:
    lr: 0.01
    weight_decay: .001

loss:
  name: MaskedMAELoss

model:
  name: OursLSTM
  OursLSTM:
    n_hist: 12
    n_pred: 12
    n_graphconv: 10
    hidden_size: 16
    n_rnn_layers: 2
    input_dim: 2
    output_dim: 1
    num_node: 207
    edge_dim: 2
    node_dim: 8
    order: 1
    dropout: 0.3

scheduler:
  name: ReduceLROnPlateau
  ReduceLROnPlateau:
    factor: 0.1
    patience: 2
    threshold: 0.001
    min_lr: 0.000001
  StepLR:
    step_size: 10
    gamma: 0.1
  MultiStepLR:
    milestones: [20, 30, 40, 50]
    gamma: 0.1