name: Ours

device: 1
data:
  dataset: METR-LA
  batch-size: 64
  input_dim: 2
  output_dim: 1

train:
  epochs: 100
  early_stop_steps: 10
  max_grad_norm: 5

optimizer:
  name: Adam
  Adam:
    lr: 0.001
    weight_decay: 0.0001
  RMSprop:
    lr: 0.01
    weight_decay: 0.001

loss:
  name: MaskedMAELoss

model:
  name: Ours
  Ours:
    dynamic_bias: null
    num_node: 207
    n_in: 2
    n_out: 1
    n_hist: 12
    n_pred: 12
    node_dim: 100
    edge_dim: 4
    n_residuals: 16
    n_dilations: 16
    n_skips: 128
    n_ends: 256
    kernel_size: 2
    n_blocks: 4
    n_layers: 2
    order: 1
    dropout: 0.3

scheduler:
  name: ReduceLROnPlateau
  ReduceLROnPlateau:
    factor: 0.2
    patience: 0
    threshold: 0.001
    min_lr: 0.0000001
  StepLR:
    step_size: 10
    gamma: 0.1
  MultiStepLR:
    milestones: [20, 30, 40, 50]
    gamma: 0.1