name: STMETANET

device: 1
data:
  dataset: METR-LA
  batch-size: 32
  input_dim: 9
  output_dim: 1

train:
  epochs: 100
  max_grad_norm: 5

optimizer:
  name: Adam
  Adam:
    lr: 0.01
    weight_decay: 0.001
    eps: 0.001
    amsgrad: true
  RMSprop:
    lr: 0.01
    weight_decay: 0.001

loss:
  name: MaskedMAELoss

model:
  name: STMETANET
  STMETANET:
    n_neighbors: 8
    n_preds: 12
    input_dim: 9
    output_dim: 1
    rnn_types: [NormalGRU, MetaGRU]
    rnn_hiddens: [32, 32]
    meta_hiddens: [16, 2]
    cl_decay_steps: 2000
    geo_hiddens: [20, 32, 32]

scheduler:
  name: ReduceLROnPlateau
  ReduceLROnPlateau:
    factor: 0.1
    patience: 5
    threshold: 0.1
    min_lr: 0.000002
  StepLR:
    step_size: 10
    gamma: 0.1
  MultiStepLR:
    milestones: [1, 5, 10, 15, 20]
    gamma: 0.1